### ISSUE TITLE
Problem when calling the  services..AddAspNetIdentity<ApplicationUser>()

### ISSUE THREAD

**Issue by ccebreros1** [IdentityServer/IdentityServer4.AspNetIdentity#44]
Ran the Identity server, and on the Startup.cs the following problem happens. Appears to be when calling the following: 
- services..AddAspNetIdentity<ApplicationUser>()

Using Asp.Net Core 2.0 and the Identity Server 4 2.0 

### Relevant parts of the log file

{System.ArgumentException: GenericArguments[1], 'Project.Identity.Models.ApplicationUser', on 'IdentityServer4.AspNetIdentity.Decorator`2[TService,TImpl]' violates the constraint of type 'TImpl'. ---> System.TypeLoadException: GenericArguments[1], 'Project.Identity.Models.ApplicationUser', on 'IdentityServer4.AspNetIdentity.Decorator`2[TService,TImpl]' violates the constraint of type parameter 'TImpl'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddDecorator[TService](IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddTransientDecorator[TService,TImplementation](IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddAspNetIdentity[TUser](IIdentityServerBuilder builder)
   at Project.Identity.Startup.ConfigureServices(IServiceCollection services)

**Comment by ccebreros1** [comment]
Looks like it is because the .AddClaimsPrincipalFactory<ApplicationUser>() here:
`services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddClaimsPrincipalFactory<ApplicationUser>();`

**Comment by brockallen** [comment]
Ah, that API is no longer needed/used. 

Also, we just released 2.0.0, so try that one now please.

**Comment by ccebreros1** [comment]
Works fine now and gets further, thanks. Now, if I want to run the migrations for the new 2.0 version an error is thrown to me:

Unable to create an object of type 'PersistedGrantDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<PersistedGrantDbContext>' to the project, or
 see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

If I add an implementation of it with the PersistedGrantDbContext the following is thrown:
Constructor on type 'IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext' not found.

I did update the Program.cs to the Core 2.0 standards as directed in Microsoft's page, but still have this issue.

**Comment by brockallen** [comment]
I'll close this, as your original issue was sorted out. As for the migrations, that sounds like an EF issue and unrelated to ASP.NET Identity. Specifically for the DB, I'll leave this from the docs here for you: http://docs.identityserver.io/en/release/reference/ef.html#database-creation-and-schema-changes-across-different-versions-of-identityserver
